In [29]:
# Import NumPy Library
import numpy as np

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


# **NUMPY ARRAYS**



In [30]:
arr = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32)

print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [31]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


In [32]:
# declare two arrays
a = np.array([0, 1])
b = np.array([9, 8])
# giving the adress to c
c = a
print('Array a: {}'.format(repr(a)))
# changing a[0] value with changing c[0]
c[0] = 5
print('Array a: {}'.format(repr(a)))

# copying b to d
d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [33]:
# declare np array a and testing type of array
arr = np.array([0, 1, 2])
print(arr.dtype)

# changing type
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [34]:
# NaN
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
# np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


In [35]:
# infinity
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# will result an OverflowError
#np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


# **NUMPY BASICS**

In [36]:
# A- Ranged Data
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [37]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


In [38]:
# B- Reshaping data
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [39]:
# Flatten : to go from 2D to 1D example
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flettened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flettened shape: (8,)


In [40]:
# Transposing : to switch column with rows
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('flettened shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
flettened shape: (2, 4)


In [41]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 2, 4))
transposed = np.transpose(arr, axes=(1, 2, 0))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

arr shape: (3, 2, 4)
transposed shape: (2, 4, 3)


In [42]:
# Zeros and ones
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [43]:
# print a table like anothers shape filled with zeros
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


# **MATH**

In [44]:
# A- Arithmetic

# Declare an Array
arr = np.array([[1, 2], [2, 3]])

# Add 1 to element values
print(repr(arr + 1))

# Substract element values by 1.2
print(repr(arr - 1.2))

# Double element values
print(repr(arr * 2))

# Halve element values
print(repr(arr / 2))

# Integer division (half)
print(repr(arr // 2))

# Square element values
print(repr(arr ** 2))

# Square root element values
print(repr(arr ** 0.5))

array([[2, 3],
       [3, 4]])
array([[-0.2,  0.8],
       [ 0.8,  1.8]])
array([[2, 4],
       [4, 6]])
array([[0.5, 1. ],
       [1. , 1.5]])
array([[0, 1],
       [1, 1]])
array([[1, 4],
       [4, 9]])
array([[1.        , 1.41421356],
       [1.41421356, 1.73205081]])


In [45]:
# define a function
def f2c(temps):
  return(5 / 9) * (temps - 32)
fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


In [46]:
# B- Non-linear functions

arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))

# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])

# Natural logarithm
print(repr(np.log(arr2)))

# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [47]:
arr = np.array([[1, 2], [3, 4]])

# Raise 3 to powe of each number in arr
print(repr(np.power(3, arr)))

arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [48]:
# C- Matrix Multiplication

arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
# print multuplication of 2 matrices
print(repr(np.matmul(arr1, arr2)))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

# This will result in valueError
#print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


# **RANDOM**

In [49]:
# A- Random integers

print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14, size=(2, 3))
print(repr(random_arr))

3
4
5
array([[13, 10,  6],
       [12, -3,  1]])


In [50]:
# B- Utility functions

np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(100))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
37
array([[15, 75],
       [12, 78]])


In [51]:
# shuffle funtion

vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([3, 4, 2, 5, 1])
array([5, 3, 4, 2, 1])
array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])


In [52]:
# C- Distributions
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=3.4, high=5.9, size=(2, 2))))


0.3132735169322751
0.4408281904196243
array([0.44345289, 0.22957721, 0.53441391])
array([[5.68490506, 4.54301202],
       [4.47674642, 5.74781947]])


In [53]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))

0.7252740646272712
4.772112039383628
array([[ 2.07318791, -2.17754724],
       [-0.89337346, -0.89545991]])


In [59]:
# D- Custom sampling

colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01])))

blue
array(['red', 'green'], dtype='<U5')
array([['red', 'red'],
       ['red', 'blue']], dtype='<U5')


# **INDEXING**

In [60]:
# A- Array Accessing

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])
print(arr[4])

arr = np.array([[6, 3], [0, 2]])
# Subarray
print(repr(arr[0]))

1
5
array([6, 3])


In [61]:
# B- Slicing

arr = np.array([1, 2, 3, 4, 5])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[2:4]))
print(repr(arr[:-1]))
print(repr(arr[-2:]))

array([1, 2, 3, 4, 5])
array([2, 3, 4, 5])
array([3, 4])
array([1, 2, 3, 4])
array([4, 5])


In [65]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(repr(arr[:]))
print(repr(arr[1:]))
print(repr(arr[:, -1]))
print(repr(arr[:, 1:]))
print(repr(arr[0:1, 1:]))
print(repr(arr[0, 1:]))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
array([[4, 5, 6],
       [7, 8, 9]])
array([3, 6, 9])
array([[2, 3],
       [5, 6],
       [8, 9]])
array([[2, 3]])
array([2, 3])
2


In [63]:
# C- Argmin and argmax

arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, 1]])
print(np.argmin(arr[0]))
print(np.argmax(arr[2]))
print(np.argmin(arr))

2
1
5


In [64]:
arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [-3, 9, -1]])

print(repr(np.argmin(arr, axis=0)))
print(repr(np.argmin(arr, axis=1)))
print(repr(np.argmax(arr, axis=-1)))

array([2, 0, 1])
array([2, 2, 0])
array([1, 1, 1])


# **FILTERING**

In [67]:
# A-filtering Data

arr = np.array([[0, 2, 3],
                [1, 3, -6],
                [-3, -2, 1]])

print(repr(arr == 3))
print(repr(arr > 0))
print(repr(arr != 1))

# Negated from the previous step
print(repr(~(arr != 1)))

array([[False, False,  True],
       [False,  True, False],
       [False, False, False]])
array([[False,  True,  True],
       [ True,  True, False],
       [False, False,  True]])
array([[ True,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])
array([[False, False, False],
       [ True, False, False],
       [False, False,  True]])


In [69]:
arr = np.array([[0, 2, np.nan],
                [1, np.nan, 6],
                [np.nan, -2, 1]])
print(repr(np.isnan(arr)))

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False]])


In [70]:
# B- Filtering in Numpy

print(repr(np.where([True, False, True])))

arr = np.array([0, 3, 5, 3, 1])
print(repr(np.where(arr == 3)))

arr = np.array([[0, 2, 3],
                [1, 0, 0],
                [-3, 0, 0]])

x_ind, y_ind = np.where(arr != 0)
print(repr(x_ind))      # x indices of non-zero elements
print(repr(y_ind))      # y indices of non-zero elements
print(repr(arr[x_ind, y_ind]))

(array([0, 2]),)
(array([1, 3]),)
array([0, 0, 1, 2])
array([1, 2, 0, 0])
array([ 2,  3,  1, -3])


In [71]:
np_filter = np.array([[True, False], [False, True]])
positives = np.array([[1, 2], [3, 4]])
negatives = np.array([[-1, -5], [-1, -8]])

print(repr(np.where(np_filter, positives, negatives)))

np_filter = positives > 2
print(repr(np.where(np_filter, positives, negatives)))

np_filter = negatives > 0
print(repr(np.where(np_filter, positives, negatives)))

array([[ 1, -5],
       [-1,  4]])
array([[-1, -5],
       [ 3,  4]])
array([[-1, -5],
       [-1, -8]])


In [72]:
# C- Axis-wise filtering

arr = np.array([[-2, -1, -3],
                [4, 5, -6],
                [3, 9, 1]])
print(repr(arr > 0))
print(np.any(arr > 0))
print(np.all(arr > 0))

array([[False, False, False],
       [ True,  True, False],
       [ True,  True,  True]])
True
False


In [74]:
arr = np.array([[-2, -1, -3],
               [4, 5, -6],
               [3, 9, 2]])

has_positive = np.any(arr > 0, axis=1)
print(has_positive)
print(repr(arr[np.where(has_positive)]))

[False  True  True]
array([[ 4,  5, -6],
       [ 3,  9,  2]])


In [75]:
help(np.where)

Help on function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called when x and y

# **STATISTICS**

In [78]:
# A- Analysis

arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

print("Min           : ", arr.min())
print("Max           : ", arr.max())

print("Representation: ", repr(arr.min(axis=0)))
print("Representation: ", repr(arr.max(axis=-1)))

Min           :  -60
Max           :  72
Representation:  array([ -3,  -2, -60])
Representation:  array([72,  3,  4])


In [79]:
# B- Statistical Metrics

arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print("Mean          : ", np.mean(arr))
print("Var           : ", np.var(arr))
print("Median        : ", np.median(arr))
print("Representation: ", repr(np.median(arr, axis=-1)))

Mean          :  2.0
Var           :  977.3333333333334
Median        :  1.0
Representation:  array([ 3.,  1., -2.])


# **AGGREGATION**

In [81]:
# A- Summation

arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])

print("SUM arr                   : ", np.sum(arr))
print("Representation SUM axis=0 : ", repr(np.sum(arr, axis=0)))
print("Representation SUM axis=1 : ", repr(np.sum(arr, axis=1)))

SUM arr                   :  18
Representation SUM axis=0 :  array([ -2,  73, -53])
Representation SUM axis=1 :  array([ 75, -56,  -1])


In [82]:
arr = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
print("Representation cumsum        : ", repr(np.cumsum(arr)))
print("Representation cumsum axis=0 : ", repr(np.cumsum(arr, axis=0)))
print("Representation cumsum axis=1 : ", repr(np.cumsum(arr, axis=1)))

Representation cumsum        :  array([ 0, 72, 75, 76, 79, 19, 16, 14, 18])
Representation cumsum axis=0 :  array([[  0,  72,   3],
       [  1,  75, -57],
       [ -2,  73, -53]])
Representation cumsum axis=1 :  array([[  0,  72,  75],
       [  1,   4, -56],
       [ -3,  -5,  -1]])


In [83]:
# B- concatenation

arr1 = np.array([[0, 72, 3],
                [1, 3, -60],
                [-3, -2, 4]])
arr2 = np.array([[-15, 6, 1],
                [8, 9, -4],
                [5, -21, 18]])
print("Representation of Concatenation arr1 and arr2        : ", repr(np.concatenate([arr1, arr2])))
print("Representation of Concatenation arr1 and arr2 axis=1 : ", repr(np.concatenate([arr1, arr2], axis=1)))
print("Representation of Concatenation arr2 and arr1 axis=1 : ", repr(np.concatenate([arr2, arr1], axis=1)))

Representation of Concatenation arr1 and arr2        :  array([[  0,  72,   3],
       [  1,   3, -60],
       [ -3,  -2,   4],
       [-15,   6,   1],
       [  8,   9,  -4],
       [  5, -21,  18]])
Representation of Concatenation arr1 and arr2 axis=1 :  array([[  0,  72,   3, -15,   6,   1],
       [  1,   3, -60,   8,   9,  -4],
       [ -3,  -2,   4,   5, -21,  18]])
Representation of Concatenation arr2 and arr1 axis=1 :  array([[-15,   6,   1,   0,  72,   3],
       [  8,   9,  -4,   1,   3, -60],
       [  5, -21,  18,  -3,  -2,   4]])


# **SAVING DATA**

In [89]:
# A- Saving

arr = np.array([5, 6, 3])

# Saves to arr.npy
np.save('arr.npy', arr)

# Also saves to 'arr.npy'
#np.save('arr', arr)

In [91]:
# B- Loading

arr = np.array([1, 2,3])
np.save('arr.npy', arr)

load_arr = np.load('arr.npy')

print("Representation of loaded arr : ", repr(load_arr))

# Will result a FileNotFound
#load_arr = np.load('arr')

Representation of loaded arr :  array([1, 2, 3])
