In [ ]:
# Import NumPy Library
import numpy as np

# Initializing a NumPy array
arr = np.array([-1, 2, 5], dtype=np.float32)

# Print the representation of the array
print(repr(arr))

array([-1.,  2.,  5.], dtype=float32)


# **NUMPY ARRAYS**



In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5]], dtype=np.float32)

print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [ ]:
arr = np.array([0, 0.1, 2])
print(repr(arr))

array([0. , 0.1, 2. ])


In [ ]:
# declare two arrays
a = np.array([0, 1])
b = np.array([9, 8])
# giving the adress to c
c = a
print('Array a: {}'.format(repr(a)))
# changing a[0] value with changing c[0]
c[0] = 5
print('Array a: {}'.format(repr(a)))

# copying b to d
d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(b)))

Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([9, 8])


In [ ]:
# declare np array a and testing type of array
arr = np.array([0, 1, 2])
print(arr.dtype)

# changing type
arr = arr.astype(np.float32)
print(arr.dtype)

int64
float32


In [ ]:
# NaN
arr = np.array([np.nan, 1, 2])
print(repr(arr))

arr = np.array([np.nan, 'abc'])
print(repr(arr))

# Will result in a ValueError
# np.array([np.nan, 1, 2], dtype=np.int32)

array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


In [ ]:
# infinity
print(np.inf > 1000000)

arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 1])
print(repr(arr))

# will result an OverflowError
#np.array([np.inf, 3], dtype=np.int32)

True
array([inf,  5.])
array([-inf,   1.])


# **NUMPY BASICS**

In [ ]:
# A- Ranged Data
arr = np.arange(5)
print(repr(arr))

arr = np.arange(5.1)
print(repr(arr))

arr = np.arange(-1, 4)
print(repr(arr))

arr = np.arange(-1.5, 4, 2)
print(repr(arr))

array([0, 1, 2, 3, 4])
array([0., 1., 2., 3., 4., 5.])
array([-1,  0,  1,  2,  3])
array([-1.5,  0.5,  2.5])


In [ ]:
arr = np.linspace(5, 11, num=4)
print(repr(arr))

arr = np.linspace(5, 11, num=4, endpoint=False)
print(repr(arr))

arr = np.linspace(5, 11, num=4, dtype=np.int32)
print(repr(arr))

array([ 5.,  7.,  9., 11.])
array([5. , 6.5, 8. , 9.5])
array([ 5,  7,  9, 11], dtype=int32)


In [ ]:
# B- Reshaping data
arr = np.arange(8)

reshaped_arr = np.reshape(arr, (2, 4))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

reshaped_arr = np.reshape(arr, (-1, 2, 2))
print(repr(reshaped_arr))
print('New shape: {}'.format(reshaped_arr.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
New shape: (2, 4)
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])
New shape: (2, 2, 2)


In [ ]:
# Flatten : to go from 2D to 1D example
arr = np.arange(8)
arr = np.reshape(arr, (2, 4))
flattened = arr.flatten()
print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(flattened))
print('flettened shape: {}'.format(flattened.shape))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])
arr shape: (2, 4)
array([0, 1, 2, 3, 4, 5, 6, 7])
flettened shape: (8,)


In [ ]:
# Transposing : to switch column with rows
arr = np.arange(8)
arr = np.reshape(arr, (4, 2))
transposed = np.transpose(arr)

print(repr(arr))
print('arr shape: {}'.format(arr.shape))
print(repr(transposed))
print('flettened shape: {}'.format(transposed.shape))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])
arr shape: (4, 2)
array([[0, 2, 4, 6],
       [1, 3, 5, 7]])
flettened shape: (2, 4)


In [ ]:
arr = np.arange(24)
arr = np.reshape(arr, (3, 2, 4))
transposed = np.transpose(arr, axes=(1, 2, 0))
print('arr shape: {}'.format(arr.shape))
print('transposed shape: {}'.format(transposed.shape))

arr shape: (3, 2, 4)
transposed shape: (2, 4, 3)


In [ ]:
# Zeros and ones
arr = np.zeros(4)
print(repr(arr))

arr = np.ones((2, 3))
print(repr(arr))

arr = np.ones((2, 3), dtype=np.int32)
print(repr(arr))

array([0., 0., 0., 0.])
array([[1., 1., 1.],
       [1., 1., 1.]])
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)


In [ ]:
# print a table like anothers shape filled with zeros
arr = np.array([[1, 2], [3, 4]])
print(repr(np.zeros_like(arr)))

arr = np.array([[0., 1.], [1.2, 4.]])
print(repr(np.ones_like(arr)))
print(repr(np.ones_like(arr, dtype=np.int32)))

array([[0, 0],
       [0, 0]])
array([[1., 1.],
       [1., 1.]])
array([[1, 1],
       [1, 1]], dtype=int32)


# **MATH**

In [ ]:
# A- Arithmetic

# Declare an Array
arr = np.array([[1, 2], [2, 3]])

# Add 1 to element values
print(repr(arr + 1))

# Substract element values by 1.2
print(repr(arr - 1.2))

# Double element values
print(repr(arr * 2))

# Halve element values
print(repr(arr / 2))

# Integer division (half)
print(repr(arr // 2))

# Square element values
print(repr(arr ** 2))

# Square root element values
print(repr(arr ** 0.5))

array([[2, 3],
       [3, 4]])
array([[-0.2,  0.8],
       [ 0.8,  1.8]])
array([[2, 4],
       [4, 6]])
array([[0.5, 1. ],
       [1. , 1.5]])
array([[0, 1],
       [1, 1]])
array([[1, 4],
       [4, 9]])
array([[1.        , 1.41421356],
       [1.41421356, 1.73205081]])


In [ ]:
# define a function
def f2c(temps):
  return(5 / 9) * (temps - 32)
fahrenheits = np.array([32, -4, 14, -40])
celsius = f2c(fahrenheits)
print('Celsius: {}'.format(repr(celsius)))

Celsius: array([  0., -20., -10., -40.])


In [ ]:
# B- Non-linear functions

arr = np.array([[1, 2], [3, 4]])
# Raised to power of e
print(repr(np.exp(arr)))

# Raised to power of 2
print(repr(np.exp2(arr)))

arr2 = np.array([[1, 10], [np.e, np.pi]])

# Natural logarithm
print(repr(np.log(arr2)))

# Base 10 logarithm
print(repr(np.log10(arr2)))

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])
array([[ 2.,  4.],
       [ 8., 16.]])
array([[0.        , 2.30258509],
       [1.        , 1.14472989]])
array([[0.        , 1.        ],
       [0.43429448, 0.49714987]])


In [ ]:
arr = np.array([[1, 2], [3, 4]])

# Raise 3 to powe of each number in arr
print(repr(np.power(3, arr)))

arr2 = np.array([[10.2, 4], [3, 5]])
# Raise arr2 to power of each number in arr
print(repr(np.power(arr2, arr)))

array([[ 3,  9],
       [27, 81]])
array([[ 10.2,  16. ],
       [ 27. , 625. ]])


In [ ]:
# C- Matrix Multiplication

arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
# print multuplication of 2 matrices
print(repr(np.matmul(arr1, arr2)))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))

# This will result in valueError
#print(repr(np.matmul(arr3, arr3)))

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


# **RANDOM**

In [ ]:
# A- Random integers

print(np.random.randint(5))
print(np.random.randint(5))
print(np.random.randint(5, high=6))

random_arr = np.random.randint(-3, high=14, size=(2, 3))
print(repr(random_arr))

4
0
5
array([[-2, 11,  0],
       [12, 13, 12]])


In [ ]:
# B- Utility functions

np.random.seed(1)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# New seed
np.random.seed(2)
print(np.random.randint(10))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

# Original seed
np.random.seed(1)
print(np.random.randint(100))
random_arr = np.random.randint(3, high=100, size=(2, 2))
print(repr(random_arr))

5
array([[15, 75],
       [12, 78]])
8
array([[18, 75],
       [25, 46]])
37
array([[15, 75],
       [12, 78]])


In [ ]:
# shuffle funtion

vec = np.array([1, 2, 3, 4, 5])
np.random.shuffle(vec)
print(repr(vec))
np.random.shuffle(vec)
print(repr(vec))

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.random.shuffle(matrix)
print(repr(matrix))

array([1, 5, 3, 4, 2])
array([4, 2, 1, 5, 3])
array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])


In [ ]:
# C- Distributions
print(np.random.uniform())
print(np.random.uniform(low=-1.5, high=2.2))
print(repr(np.random.uniform(size=3)))
print(repr(np.random.uniform(low=3.4, high=5.9, size=(2, 2))))


0.2936141483736795
-0.43523124723050954
array([0.13002857, 0.01936696, 0.67883553])
array([[3.92907029, 4.06386665],
       [4.6289329 , 3.53340636]])


In [ ]:
print(np.random.normal())
print(np.random.normal(loc=1.5, scale=3.5))
print(repr(np.random.normal(loc=-2.4, scale=4.0, size=(2, 2))))

0.3001703199558275
0.2671255372726846
array([[-6.97007279, -3.79737089],
       [-3.23557693, -0.05350724]])


In [ ]:
# D- Custom sampling

colors = ['red', 'blue', 'green']
print(np.random.choice(colors))
print(repr(np.random.choice(colors, size=2)))
print(repr(np.random.choice(colors, size=(2, 2), p=[0.8, 0.19, 0.01])))

green
array(['green', 'green'], dtype='<U5')
array([['red', 'red'],
       ['red', 'red']], dtype='<U5')
